version: "3.9"
services:
   shop:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      SESSION: $SESSION
      OWNER_ID: $OWNER_ID
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_URI: $DATABASE_URI
      TO_CHANNEL: $TO_CHANNEL
      COLLECTION_NAME: $COLLECTION_NAME
      BOT_USERNAME: $BOT_USERNAME
 
